INSERT INTO FRAMEWORK_TYPE(FRAMEWORK_TYPE_ID,FRAMEWORK_NAME) VALUES (1,"Spring-Boot");
INSERT INTO FRAMEWORK_TYPE(FRAMEWORK_TYPE_ID,FRAMEWORK_NAME) VALUES (2,"Django");
INSERT INTO FRAMEWORK_TYPE(FRAMEWORK_TYPE_ID,FRAMEWORK_NAME) VALUES (3,"Vue.js");
INSERT INTO FRAMEWORK_TYPE(FRAMEWORK_TYPE_ID,FRAMEWORK_NAME) VALUES (4,"React");
INSERT INTO FRAMEWORK_TYPE(FRAMEWORK_TYPE_ID,FRAMEWORK_NAME) VALUES (5,"MySQL");

-- 위는 들어가고 아래는 초기화가 안됨 왜지?
--TODO / SQL : 이거 처음 run 만 입력되고 다음부턴 없어지지않고 중복으로 나타남..
INSERT INTO FRAMEWORK(FRAMEWORK_ID,BUILD_TYPE,VERSION,FRAMEWORK_TYPE_ID) VALUES (1,"gradle","2.6,4",1);
INSERT INTO FRAMEWORK(FRAMEWORK_ID,BUILD_TYPE,VERSION,FRAMEWORK_TYPE_ID) VALUES (2,"maven","2.5,4",1);
INSERT INTO FRAMEWORK(FRAMEWORK_ID,BUILD_TYPE,VERSION,FRAMEWORK_TYPE_ID) VALUES (3,"gradle","2.4,4",1);
INSERT INTO FRAMEWORK(FRAMEWORK_ID,VERSION,FRAMEWORK_TYPE_ID) VALUES (4,"11.0.14",2);
INSERT INTO FRAMEWORK(FRAMEWORK_ID,VERSION,FRAMEWORK_TYPE_ID) VALUES (5,"11.0.14",2);
INSERT INTO FRAMEWORK(FRAMEWORK_ID,VERSION,FRAMEWORK_TYPE_ID) VALUES (6,"11.0.14",2);
INSERT INTO FRAMEWORK(FRAMEWORK_ID,VERSION,FRAMEWORK_TYPE_ID) VALUES (7,"11.0.14",2);
INSERT INTO FRAMEWORK(FRAMEWORK_ID,VERSION,FRAMEWORK_TYPE_ID) VALUES (8,"3.12",3);
INSERT INTO FRAMEWORK(FRAMEWORK_ID,VERSION,FRAMEWORK_TYPE_ID) VALUES (9,"1.23",3);
INSERT INTO FRAMEWORK(FRAMEWORK_ID,VERSION,FRAMEWORK_TYPE_ID) VALUES (10,"17.0.1",4);
INSERT INTO FRAMEWORK(FRAMEWORK_ID,VERSION,FRAMEWORK_TYPE_ID) VALUES (11,"16.1.3",4);
INSERT INTO FRAMEWORK(FRAMEWORK_ID,VERSION,FRAMEWORK_TYPE_ID) VALUES (12,"8.0.26",5);
INSERT INTO FRAMEWORK(FRAMEWORK_ID,VERSION,FRAMEWORK_TYPE_ID) VALUES (13,"8.0.20",5);
INSERT INTO FRAMEWORK(FRAMEWORK_ID,VERSION,FRAMEWORK_TYPE_ID) VALUES (14,"7.0.12",5);
INSERT INTO FRAMEWORK(FRAMEWORK_ID,VERSION,FRAMEWORK_TYPE_ID) VALUES (15,"7.0.11",5);

