FROM openjdk:11 as builder

COPY . .

RUN ls -l
RUN chmod +x ./gradlew
RUN ./gradlew clean build

FROM openjdk:11
COPY --from=builder /build/libs/*.jar app.jar

ENTRYPOINT [ "java", "-jar","./app.jar" ]
